// Deterministic generator for realistic low-value auto-captured memories (session digests + command fix
// records in the exact formats SAM's capture.js produces). They are distractors: never labelled relevant.
// Run once; output is committed as data/memories_noise.txt so the benchmark is stable.
import { writeFileSync } from 'node:fs';
let seed = 1337;
const rnd = () => { seed ^= seed << 13; seed >>>= 0; seed ^= seed >>> 17; seed ^= seed << 5; seed >>>= 0; return seed / 4294967296; };
const pick = (a) => a[Math.floor(rnd() * a.length)];
const P = {
  kervan: {
    files: ['src/app/(shop)/page.tsx', 'src/components/Header.tsx', 'src/components/ProductCard.tsx', 'src/app/(shop)/kategori/[slug]/page.tsx', 'src/server/orders.ts', 'src/lib/format.ts', 'apps/admin/src/app/products/page.tsx', 'src/components/Footer.tsx', 'src/app/(account)/hesap/page.tsx', 'packages/ui/src/button.tsx', 'src/server/products.ts', 'src/hooks/useDebounce.ts'],
    intents: ['footer linklerini güncelle', 'tidy up header spacing on mobile', 'add breadcrumb to category page', 'refactor product card props', 'admin product table pagination', 'fix lint warnings', 'hesap sayfası adres formu', 'bump next to 14.2.15', 'rename helpers in format.ts', 'add loading skeletons', 'remove unused exports', 'update copy on about page'],
    cmds: [['pnpm lint', 'no-unused-vars'], ['pnpm typecheck', "TS2339: Property 'slug' does not exist"], ['pnpm test', 'expected "1.299,90 TL" got "1299.9"'], ['pnpm build', 'Dynamic server usage: cookies'], ['pnpm dev', 'EADDRINUSE :::3000']],
  },
  pulsar: {
    files: ['src/pulsar/api/projects.py', 'src/pulsar/api/accounts.py', 'src/pulsar/services/usage.py', 'src/pulsar/queries/funnels.py', 'tests/api/test_projects.py', 'src/pulsar/utils/time.py', 'docs/runbooks/ingest-lag.md', 'src/pulsar/api/schemas.py', 'sdks/js/src/index.ts', 'Makefile'],
    intents: ['add description field to projects', 'funnel query cleanup', 'typo fixes in runbook', 'usage service refactor', 'SDK README examples', 'accounts endpoint pagination', 'time utils tests', 'remove deprecated v1 field aliases', 'rename query helpers', 'Makefile targets for docs'],
    cmds: [['pytest tests/api', 'assert 404 == 200'], ['ruff check .', 'F401 imported but unused'], ['mypy src', 'Incompatible return value type'], ['make docs', 'mintlify: command not found'], ['uv run pytest -k funnels', 'KeyError: step_2']],
  },
  atlas: {
    files: ['app/(tabs)/index.tsx', 'app/(tabs)/profile.tsx', 'src/components/TripCard.tsx', 'src/components/DayTabs.tsx', 'app/trip/[id].tsx', 'src/hooks/useTrips.ts', 'src/components/EmptyState.tsx', 'src/i18n/locales/de.json', 'app/settings/index.tsx', 'src/components/Avatar.tsx'],
    intents: ['profil ekranı düzenlemeleri', 'trip card shadow tweaks', 'empty state illustration', 'German translations pass', 'day tabs animation', 'settings screen layout', 'rename useTrips selectors', 'avatar fallback initials', 'clean up unused icons', 'tab bar icon sizes'],
    cmds: [['bun run lint', 'react-hooks/exhaustive-deps'], ['bun run typecheck', "TS2322: Type 'string' is not assignable"], ['bun run test', 'Unable to find an element with text'], ['bunx expo start', 'Port 8081 is being used']],
  },
};
const out = ['# GENERATED by bench/retrieval/gen-noise.mjs — auto-captured distractors (session digests and command fix records). Never relevant.'];
let n = 0;
for (const [proj, d] of Object.entries(P)) {
  out.push('@project ' + proj);
  for (let i = 0; i < 26; i++) {
    const age = 1 + Math.floor(rnd() * 180);
    const f1 = pick(d.files), f2 = pick(d.files);
    const day = new Date(Date.UTC(2026, 9, 7) - age * 86400000).toISOString().slice(0, 10);
    out.push(`z-${proj}-s${i} | session | ${age} | | ${f1} ${f2} | ${day} ${pick(d.intents)} → ${1 + Math.floor(rnd() * 6)} edits ${f1}${f1 !== f2 ? ', ' + f2 : ''}`);
    n++;
  }
  for (let i = 0; i < 18; i++) {
    const age = 1 + Math.floor(rnd() * 150);
    const [cmd, err] = pick(d.cmds); const f = pick(d.files);
    out.push(`z-${proj}-f${i} | fix | ${age} | | ${f} | \`${cmd}\` failed (${err}) → fixed via ${f}`);
    n++;
  }
}
writeFileSync(new URL('./data/memories_noise.txt', import.meta.url), out.join('\n') + '\n');
console.log('noise memories:', n);
