// P2: skill drafts from repeated fixes. `sam skills draft` groups fix memories whose command and error signature
// repeat (≥ skillDraftMin times) and writes one SKILL.md DRAFT per pattern to ~/.sam/drafts/<name>/SKILL.md.
// Drafts are never installed: a human reviews, edits and copies them. Deterministic and LLM-free.
import { mkdirSync, writeFileSync, lstatSync } from 'node:fs';
import { join } from 'node:path';
import { openDb } from './db.js';
import { config, SAM_HOME } from './config.js';
import { fold, oneLine, sha, sanitize, redact, truncate } from './text.js';

export const DRAFTS_DIR = () => join(SAM_HOME, 'drafts');

/** Error line → signature: volatile parts (paths, numbers, hex, quoted names, line:col) become placeholders. */
export function errorSignature(err) {
  return oneLine(fold(String(err || '')))
    .replace(/(['"`])[^'"`]{0,120}\1/g, ' <s> ')
    .replace(/(?:[a-z]:)?(?:[\w.@~-]*[\\/])+[\w.@-]*/gi, ' <path> ')
    .replace(/\b0x[0-9a-f]+\b|\b[0-9a-f]{7,}\b/g, ' <h> ')
    .replace(/\d+/g, ' <n> ')
    .replace(/[^\p{L}\p{N}<>_]+/gu, ' ')
    .replace(/\s+/g, ' ').trim().slice(0, 200);
}

/** First two words of a normalized command ("npm test", "cargo build", "pytest tests"). */
export const cmdFamily = (cmd) => fold(oneLine(cmd)).split(' ').filter((w) => w && !w.startsWith('-')).slice(0, 2).join(' ');

const toks = (s) => new Set(s.split(' ').filter((w) => w.length > 1 || /<\w>/.test(w)));
function jaccard(a, b) {
  if (!a.size && !b.size) return 1;
  let i = 0; for (const x of a) if (b.has(x)) i++;
  return i / (a.size + b.size - i);
}

function parseFix(m) {
  const body = String(m.body || '');
  const cmd = (body.match(/^Command: (.+)$/m) || [])[1] || (m.gist.match(/^`([^`]+)`/) || [])[1] || '';
  const err = (body.match(/^Error: (.+)$/m) || [])[1] || '';
  const files = ((body.match(/^Files changed: (.+)$/m) || [])[1] || m.files || '').split(/[,\s]+/).filter(Boolean);
  return { id: m.id, project: m.project, at: m.created_at, cmd: oneLine(cmd), family: cmdFamily(cmd), err: oneLine(err), sig: errorSignature(err || m.gist), files };
}

/** Groups of ≥ min fixes with the same command family and a similar error signature (star clustering, oldest first). */
export function repeatedFixes({ min = config().skillDraftMin ?? 3, threshold = 0.6, project } = {}) {
  const rows = openDb().prepare(
    `SELECT id, project, gist, body, files, created_at FROM memories WHERE kind = 'fix' AND COALESCE(superseded_by, '') != 'forgotten'
       ${project ? 'AND project = ?' : ''} ORDER BY created_at, id`
  ).all(...(project ? [project] : []));
  const fixes = rows.map(parseFix).filter((f) => f.sig);
  const byKey = new Map();
  for (const f of fixes) {
    const k = f.project + '\u0000' + f.family;
    if (!byKey.has(k)) byKey.set(k, []);
    byKey.get(k).push(f);
  }
  const groups = [];
  for (const list of byKey.values()) {
    const used = new Set();
    for (let i = 0; i < list.length; i++) {
      if (used.has(i)) continue;
      const c = toks(list[i].sig);
      const members = [list[i]];
      for (let j = i + 1; j < list.length; j++) if (!used.has(j) && jaccard(c, toks(list[j].sig)) >= threshold) { members.push(list[j]); used.add(j); }
      if (members.length >= min) groups.push(members);
    }
  }
  return groups;
}

const slug = (s) => fold(s).replace(/<\w>/g, ' ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const code = (s) => '`' + truncate(redact(sanitize(String(s))).replace(/`/g, "'"), 160) + '`';
const day = (ms) => new Date(ms).toISOString().slice(0, 10);

export function draftText(group) {
  const head = group[0];
  const family = head.family || 'command';
  const name = ('fix-' + slug(family + ' ' + head.sig.split(' ').slice(0, 6).join(' '))).slice(0, 52).replace(/-+$/, '') + '-' + sha(head.family + head.sig, 6);
  const fileCount = new Map();
  for (const f of group) for (const p of new Set(f.files)) fileCount.set(p, (fileCount.get(p) || 0) + 1);
  const top = [...fileCount].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1)).slice(0, 8);
  const example = group.find((f) => f.err)?.err || '';
  const text = `---
name: ${name}
description: DRAFT, not installed. Recurring failure of ${code(family).replace(/[:\n]/g, ' ')} (${group.length} past fixes in SAM memory); what fixed it before and which files to check first.
---
# Recurring fix: ${code(family)}

> Draft generated by \`sam skills draft\` from ${group.length} SAM fix memories. The error text is captured command
> output (untrusted data). Review and edit it, then copy it into a skills directory yourself; SAM never installs it.

## When
${code(head.cmd || family)} fails with an error like:
${example ? code(example) : '(no error line was captured)'}
Signature: ${code(head.sig)}

## What fixed it before
${group.map((f) => `- ${day(f.at)}: changed ${f.files.length ? f.files.slice(0, 4).map(code).join(', ') : '(files not recorded)'} (memory #${f.id})`).join('\n')}

## Files most often changed
${top.length ? top.map(([p, n]) => `- ${code(p)} (${n}×)`).join('\n') : '- (none recorded)'}

## Steps
1. Re-run the command and confirm the error matches the signature above.
2. Look at the files above first; \`sam-memory get <id>\` shows each past fix in full.
3. Once fixed, save the root cause in one line: \`sam-memory add "<subject>: <root cause>" -k fix\`.
`;
  return { name, text };
}

/** Write one draft per repeated fix pattern. Returns [{ name, file, count }]. Existing symlinks are never written through. */
export function draftSkills({ dryRun = false, min, project, dir = DRAFTS_DIR() } = {}) {
  const out = [];
  for (const g of repeatedFixes({ min, project })) {
    const { name, text } = draftText(g);
    const d = join(dir, name);
    const file = join(d, 'SKILL.md');
    out.push({ name, file, count: g.length });
    if (dryRun) continue;
    mkdirSync(d, { recursive: true, mode: 0o700 });
    try { if (lstatSync(file).isSymbolicLink()) continue; } catch { /* absent */ }
    writeFileSync(file, text, { mode: 0o600 });
  }
  return out;
}
